 priorities = {
	-- Molten Core loot
	["Crimson Shocker"] = "MS>OS",
	["Flamewaker Legplates"] = "MS>OS",
	["Heavy Dark Iron Ring"] = "Druid (Tank) > MS>OS",
	["Manastorm Leggings"] = "MS>OS",
	["Ring of Spell Power"] = "Caster > Healers",
	["Robes of Volatile Power"] = "Paladin = Warlock > Other Casters",
	["Salamander Scale Pants"] = "Paladin = Druid (Resto) > Healers",
	["Sorcerous Dagger"] = "Caster DPS = Druid (Resto) > Priest",
	["Wristguards of Stability"] = "Druid (Feral) = Warrior (DPS)",
	["Aged Core Leather Gloves"] = "Rogue = Warrior (Dagger) > Warrior (Tank) = Warrior (Non Human)",
	["Fire Runed Grimoire"] = "MS>OS",
	["Flameguard Gauntlets"] = "MS>OS",
	["Magma Tempered Boots"] = "MS>OS",
	["Mana Igniting Cord"] = "Caster > Paladin",
	["Obsidian Edged Blade"] = "MS>OS",
	["Quick Strike Ring"] = "Druid (Feral) = Warrior (DPS) > Rogue > Hunter",
	["Sabatons of the Flamewalker"] = "Paladin",
	["Talisman of Ephemeral Power"] = "Caster > Healers",
	["Choker of Enlightenent"] = "Caster > Healers",
	["Earthshaker"] = "MS>OS",
	["Eskhandar's Right Claw"] = "MS>OS",
	["Medallion of Steadfast Might"] = "MS>OS",
	["Striker's Mark"] = "Rogue = Warrior > Hunter",
	["Aurastone Hammer"] = "Druid (Resto) = Paladin > Priest",
	["Brutality Blade"] = "Rogue = Warrior (DPS) > Hunter",
	["Drillborer Disk"] = "MS>OS",
	["Gutgore Ripper"] = "Rogue = Warrior (Non Human)",
	["Seal of the Archmagus"] = "MS>OS",
	["Shadowstrike"] = "MS>OS",
	["Azuresong Mageblade"] = "Caster > Paladin",
	["Blastershot Launcher"] = "Rogue = Warrior  > Hunter",
	["Staff of Dominance"] = "Caster > Healers",
	["Ancient Petrified Leaf"] = "Hunter",
	["Cauterizing Band"] = "MS>OS",
	["Core Forged Greaves"] = "MS>OS",
	["Core Hound Tooth"] = "Rogue = Warrior (Dagger) = Warrior (Tank) > Warrior (Non Human) > Warrior (Human) > Hunter",
	["Finkle's Lava Dredger"] = "MS>OS",
	["Fireguard Shoulders"] = "Druid (Feral) > Warrior (Tank)",
	["Fireproof Cloak"] = "Warrior (Tank) = Druid (Feral)",
	["Gloves of the Hypnotic Flame"] = "Caster",
	["Sash of Whispered Secrets"] = "Shadow Priest > Warlock",
	["The Eye of Divinity"] = "Priest",
	["Wild Growth Spaulders"] = "MS>OS",
	["Wristguards of True Flight"] = "Warrior (Tank) > Hunter = Warrior (DPS) > Paladin (Ret)",
	["Band of Accuria"] = "Rogue = Warrior (Tank) > Warrior (DPS) = Druid (Feral) > Hunter",
	["Band of Sulfuras"] = "MS>OS",
	["Bonereaver's Edge"] = "MS>OS",
	["Choker of the Fire Lord"] = "Caster > Healers",
	["Cloak of the Shrouded Mists"] = "Hunter > Rogue > Warrior (Tank)",
	["Crown of Destruction"] = "Hunter = Warrior",
	["Dragon's Blood Cape"] = "Tank > MS>OS",
	["Essence of the Pure Flame"] = "MS>OS",
	["Malistar's Defender"] = "MS>OS",
	["Onslaught Girdle"] = "Warrior (Tank) = Warrior (DPS)",
	["Perdition's Blade"] = "Rogue (Dagger) > Warrior (Non Human) > Warrior (Tank)",
	["Shard of the Flame"] = "MS>OS",
	["Spinal Reaper"] = "MS>OS",
	
	-- Onyxia loot
	["Ancient Cornerstone Grimoire"] = "MS>OS",
	["Eskhandar's Collar"] = "Druid (Feral) > MS>OS",
	["Deathbringer"] = "Warrior (Edge) > Warrior (DPS)",
	["Head of Onyxia"] = "Warrior (Tank) = Druid (Tank) = Warrior (DPS) = Rogue = Hunter",
	["Sapphiron Drape"] = "MS>OS",
	["Shard of the Scale"] = "MS>OS",
	["Ring of Binding"] = "MS>OS",
	["Vis'kag the Bloodletter"] = "Rogue (Human) = Warrior (DPS) (Human) > Rogue  = Warrior (DPS)",

	-- Blackwing Lair loot
	["Band of Dark Dominion"] = "Warlock = Shadow Priest",
	["Boots of Pure Thought"] = "Healer",
	["Cloak of Draconic Might"] = "Warrior (Tank) = Warrior (DPS) = Druid (Feral) > Rogue",
	["Doom's Edge"] = "Warrior (Edge) > Hunter",
	["Draconic Avenger"] = "(PVP) MS>OS",
	["Draconic Maul"] = "(PVP) Druid (Cat) > MS>OS",
	["Essence Gatherer"] = "MS>OS",
	["Interlaced Shadow Jerkin"] = "(PVP) MS>OS",
	["Ringo's Blizzard Boots"] = "Mage",
	["Gloves of Rapid Evolution"] = "MS>OS",
	["Mantle of the Blackwing Cabal"] = "Caster > Healer",
	["Spineshatter"] = "Warrior (DPS)",
	["The Untamed Blade"] = "(PVP) MS>OS",
	["Dragonfang Blade"] = "Rogue = Warrior (Non Human) > Warrior (Tank)",
	["Helm of Endless Rage"] = "Warrior (Tank) > Warrior (DPS)",
	["Pendant of the Fallen Dragon"] = "MS>OS",
	["Red Dragonscale Protector"] = "MS>OS",
	["Black Brood Pauldrons"] = "MS>OS",
	["Bracers of Arcane Accuracy"] = "Caster",
	["Heartstriker"] = "(PVP) MS>OS",
	["Maladath, Runed Blade of the Black Flight"] = "Rogue (Non Human) = Warrior (DPS) = Warrior (Tank)",
	["Black Ash Robe"] = "MS>OS",
	["Claw of the Black Drake"] = "MS>OS",
	["Cloak of Firemaw"] = "Rogue > Warrior (DPS)",
	["Firemaw's Clutch"] = "Shadow Priest > Mage = Warlock",
	["Legguards of the Fallen Crusader"] = "Warrior (DPS) > Paladin",
	["Band of Forced Concentration"] = "Warlock > Mage > Shadow Priest",
	["Dragonbreath Hand Cannon"] = "MS>OS",
	["Ebony Flame Gloves"] = "MS>OS",
	["Malfurion's Blessed Bulwark"] = "Druid (Feral) > MS>OS",
	["Drake Fang Talisman"] = "Tank = Warrior (DPS) = Rogue > Hunter",
	["Emberweave Leggings"] = "MS>OS",
	["Shroud of Pure Thought"] = "MS>OS",
	["Herald of Woe"] = "MS>OS",
	["Dragon's Touch"] = "MS>OS",
	["Styleen's Impeding Scarab"] = "Warrior (Tank)",
	["Circle of Applied Force"] = "Warrior (Tank) > Druid (Feral) = Warrior (DPS) > Rogue",
	["Drake Talon Cleaver"] = "MS>OS",
	["Drake Talon Pauldrons"] = "Warrior (DPS) = Warrior (Tank)",
	["Ring of Blackrock"] = "Shadow Priest > Mage = Warlock",
	["Shadow Wing Focus Staff"] = "MS>OS",
	["Taut Dragonhide Belt"] = "Druid (Bear) > Druid (Cat) = MS>OS",
	["Rejuvenating Gem"] = "Priest = Paladin = Druid (Resto)",
	["Angelista's Grasp"] = "Warlock > Priest",
	["Chromatic Boots"] = "Warrior (DPS) = Warrior (Tank) > Paladin",
	["Claw of Chromaggus"] = "Druid (Resto) > Shadow Priest > Warlock = Mage",
	["Elementium Threaded Cloak"] = "MS>OS",
	["Empowered Leggings"] = "Paladin > Priest = Druid (Resto)",
	["Girdle of the Fallen Crusader"] = "MS>OS",
	["Taut Dragonhide Gloves"] = "MS>OS",
	["Taut Dragonhide Shoulderpads"] = "Druid (Feral)",
	["Shimmering Geta"] = "MS>OS",
	["Ashjre'thul, Crossbow of Smiting"] = "Hunter",
	["Chromatically Tempered Sword"] = "Rogue (Human) = Warrior (DPS) (Human) > Rogue = Warrior (DPS)",
	["Elementium Reinforced Bulwark"] = "Warrior (Tank)",
	["Ashkandi, Greatsword of the Brotherhood"] = "MS>OS",
	["Archimtiros' Ring of Reckoning"] = "MS>OS",
	["Boots of the Shadow Flame"] = "Druid (Feral) = Rogue(Dagger) > Warrior (DPS)",
	["Cloak of the Brood Lord"] = "Caster",
	["Crul'shorukh, Edge of Chaos"] = "Warrior (Tank) Edge = Warrior (DPS) Edge > Warrior (DPS)",
	["Head of Nefarian"] = "Warrior (Tank) = Warrior (DPS) = Rogue > Hunter",
	["Mish'undare, Circlet of the Mindflayer"] = "Mage > Warlock = Paladin",
	["Prestor's Talisman of Connivery"] = "Rogue = Hunter = Druid (Feral)",
	["Pure Elementium Band"] = "MS>OS",
	["Therazane's Link"] = "MS>OS",
	["Neltharion's Tear"] = "Warlock = Mage > Shadow Priest",
	["Lok'amir il Romathis"] = "Paladin > Shadow Priest = Druid (Resto)",
	["Staff of the Shadow Flame"] = "Mage = Warlock"
}
